"""
Field length limits for use case and risk text fields.
"""

USE_CASE_DESCRIPTION_MAX_LENGTH = 1500
INTENDED_USE_MAX_LENGTH = 1000
EXPECTED_BENEFITS_MAX_LENGTH = 1000
SOLUTION_DESIGN_OVERVIEW_MAX_LENGTH = 2500
HUMAN_IN_LOOP_STRATEGY_MAX_LENGTH = 500
PROTECTED_ATTRIBUTES_MAX_LENGTH = 500
BALANCING_STRATEGY_MAX_LENGTH = 1000
RISK_DESCRIPTION_MAX_LENGTH = 1500
MITIGATION_STRATEGY_MAX_LENGTH = 1500
DATA_OWNER_MAX_LENGTH = 100
IMPACTED_STAKEHOLDER_MAX_LENGTH = 100
IMPACTED_STAKEHOLDERS_MAX_COUNT = 25

AI_ENHANCEMENT_MIN_INPUT_LENGTH = 20

AI_ENHANCEMENT_FIELD_LIMITS = {
    "description": USE_CASE_DESCRIPTION_MAX_LENGTH,
    "intended_use": INTENDED_USE_MAX_LENGTH,
    "expected_benefits": EXPECTED_BENEFITS_MAX_LENGTH,
    "solution_design_overview": SOLUTION_DESIGN_OVERVIEW_MAX_LENGTH,
    "risk_description": RISK_DESCRIPTION_MAX_LENGTH,
    "mitigation_strategy": MITIGATION_STRATEGY_MAX_LENGTH,
}

SUPPORTED_AI_ENHANCEMENT_FIELDS = tuple(AI_ENHANCEMENT_FIELD_LIMITS.keys())
